---
title: "Google Personal Analysis"
author: "Johannes Harmse"
date: "November 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.show = "animate")
```

```{r, message = FALSE}
library(tidyverse)
library(rjson)
library(lubridate)
library(forcats)
library(countrycode)
# devtools::install_github("dgrtwo/gganimate")
library(gganimate)
library(ggmap)
library(animation)
```

```{r}
# browse_hist <- fromJSON(file = "../data/Chrome/BrowserHistory.json")
location_hist <- fromJSON(file = "../data/Location History/Location History.json")
```

```{r}
# browse_hist[[1]][1]
```

```{r}
location_hist[[1]][1]
```

```{r}
as_datetime(as.numeric(substr(location_hist[[1]][[1]][[1]], 1, nchar(location_hist[[1]][[1]][[1]])-3)), 
            tz = "America/Vancouver")
```

```{r}
location_df <- data_frame(time = sapply(1:length(location_hist[[1]]), function(x) location_hist[[1]][[x]]$timestampMs), 
                          lat = sapply(1:length(location_hist[[1]]), function(x) location_hist[[1]][[x]]$latitudeE7), 
                          long = sapply(1:length(location_hist[[1]]), function(x) location_hist[[1]][[x]]$longitudeE7), 
                          accuracy = sapply(1:length(location_hist[[1]]), function(x) location_hist[[1]][[x]]$accuracy), 
                          altitude = sapply(1:length(location_hist[[1]]), function(x) location_hist[[1]][[x]]$altitude))
```

```{r}
location_df <- location_df %>% 
  mutate(time = as_datetime(as.numeric(time)/1000), 
         long = round(long/10^7, 3), 
         lat = round(lat/10^7, 3))
```

```{r}
location_summary <- location_df %>% 
  arrange(time) %>% 
  mutate(lag_lat = lag(lat), lag_long = lag(long), day = ymd(substr(as.character(time), 1, 10))) %>% 
  select(time, lag_lat, lat, lag_long, long, day)
```

```{r}

mapData <- get_googlemap(center = c(0, 0), zoom = 1, maptype = "terrain", source = "google", size = c(360, 240), scale = 1)

# mapData <- map_data("world") %>%
# 		mutate(ISO = countrycode(region, "country.name", "iso2c"), 
# 		       lat_cat = lat, 
# 		       long_cat = long)
#mapData <- get_map(location = c(-122.080954, 36.971709), maptype = "terrain", source = "google", zoom = 14)
# mapData <- get_googlemap(center = c(0, 0), # center = c(location_summary$lag_long[[2]], location_summary$lag_lat[[2]]), 
#   maptype = "roadmap", 
#                          zoom = 1, 
#                          size = c(144, 144), scale = 1)

# # ggplot(location_summary, colour = time) + 
#   ggmap(mapData) + 
#     ggplot(location_summary[1:1000, ], frame = time) + 
#   geom_segment(data = location_summary, aes(x = lag_long, xend = long, y = lag_lat, yend = lat, colour = time))

ggmap(mapData)



```

```{r}
plot_map <- function(location_summary, period = 10){
  location_summary <- location_summary
  
  ggmapdata <- ggmap(mapData)
    
    temp_filt <- location_summary
  
    start = 1
    start_plot = 1
    lat_start = 0
    long_start = 0
     
    plot_seq <- seq(period, nrow(temp_filt), 1)
    
    temp = data_frame()
    
    for (count in 1:length(unique(temp_filt$day))){
      temp[nrow(temp) + 1, "period" ] = unique(temp_filt$day)[count]
      temp[nrow(temp), "long_avg"] = mean(unlist(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "long"][as.integer(seq(1, nrow(temp_filt[temp_filt$day == unique(temp_filt$day)[count], ]), length.out = 50)), ]), na.rm = TRUE)
      temp[nrow(temp), "lat_avg"] = mean(unlist(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "lat"][as.integer(seq(1, nrow(temp_filt[temp_filt$day == unique(temp_filt$day)[count], ]), length.out = 50)), ]), na.rm = TRUE)
      # temp[nrow(temp), "long_min"] = min(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "long"])
      # temp[nrow(temp), "long_max"] = max(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "long"])
      # temp[nrow(temp), "lat_min"] = min(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "lat"])
      # temp[nrow(temp), "lat_max"] = max(temp_filt[temp_filt$day == unique(temp_filt$day)[count], "lat"])
    }
    
    # for (count in 1:length(plot_seq)){
    #   if((abs(max(temp_filt$lat[start:(plot_seq[count])]) - 
    #          min(temp_filt$lat[start:(plot_seq[count])])) > 2.5 || 
    #       abs(max(temp_filt$long[start:(plot_seq[count])]) - 
    #          min(temp_filt$long[start:(plot_seq[count])])) > 2.5) && 
    #      (interval(min(temp_filt$time[start:(plot_seq[count])]),  
    #          max(temp_filt$time[start:(plot_seq[count])]))/ddays(1) > 0)){
    #     
    #     # plot_period <- start_plot:plot_seq[count]
    #     ## plot_period <- seq(start_plot, plot_seq[count], length.out = ifelse(plot_seq[count] - start > 5, 5, 
    #     ##                                                                   plot_seq[count] - start))  
    #     
    #     # temp_add <- temp_filt[plot_period, ]
    #     # temp_add$period <- start_plot
    #     
    #     temp_filt[start:plot_seq[count], "period"] = start_plot
    #     temp_filt[start:plot_seq[count], "long_min"] = min(temp_filt[start:plot_seq[count], "long"])
    #     temp_filt[start:plot_seq[count], "lat_min"] = min(temp_filt[start:plot_seq[count], "lat"])
    #     temp_filt[start:plot_seq[count], "long_max"] = max(temp_filt[start:plot_seq[count], "long"])
    #     temp_filt[start:plot_seq[count], "lat_max"] = max(temp_filt[start:plot_seq[count], "lat"])
    #     
    #     # point_add <- c(mean(temp_add$lat), mean(temp_add$long))
    #     
    #     # temp_add <- temp_filt[plot_period, ]
    #     
    #     # if(nrow(temp) == 0){
    #     #   temp <- temp_add
    #     # }else{
    #     #   temp <- rbind(temp, temp_add)
    #     # }
    #     
    #     start_plot = plot_seq[count]
    #     start = plot_seq[count]
    #     #start_plot = start
    #     #start = plot_seq[count-1]
    #     
    #   }
    # }
    
    # temp <- temp_filt
    
    for (counter in 1:nrow(temp)){
      temp_sq <- temp[1:counter, ]
      coord_sq <- data_frame(x_sq = unlist(temp_sq$long_avg), y_sq = unlist(temp_sq$lat_avg))
      # coord_sq <- data_frame(x_sq = unlist(list(rep(temp_sq$long_min, 2), rep(temp_sq$long_max, 2))), 
      # y_sq = unlist(list(temp_sq$lat_min, rep(temp_sq$lat_max, 2), temp_sq$lat_min)))
      # # temp_sq_long <- unlist(temp[temp$period == unique(temp$period)[period], c("long_min", "long_max")])
      # # temp_sq_lat <- unlist(temp[temp$period == unique(temp$period)[period], c("long_min", "long_max")])
      # # p <- ggmapdata + 
      #   #   geom_path(data = temp, size = 1, aes(x = long, y = lat, colour = time)) + 
      #   #   labs(title = "Location Data") + 
      #   #   scale_color_gradientn(colours = terrain.colors(10))
      
      # coord_sq <- temp[temp$period == unique(temp$period)[period], ]
      
      # if (period == 1){
      #   p <- ggmapdata
      # }
      
      p <- ggmapdata + 
        geom_point(data = coord_sq, aes(x = x_sq, 
                                         y = y_sq), 
                     alpha = 0.25, fill = "red", size = 2, 
                     colour = "red")
      
      # p <- p + 
      #   stat_ellipse(data = temp[temp$period == unique(temp$period)[period], ], aes(x = long, 
      #                          y = lat), alpha = 0.25)
      
      print(p)
    }
    
}
```

```{r}
# npoints = 100
# oopt = ani.options(interval = 1, nmax = npoints)

# animation::saveGIF(plot_map(),interval = 0.1, width = 580, height = 400)

saveHTML({plot_map(location_summary, period = 10)}, img.name = "anim_plot", imgdir = "anim_dir", 
         htmlfile = "anim.html", autobrowse = FALSE, title = "Travel", 
         verbose =FALSE, interval = 0.25, ani.width = 480, ani.height = 480)

graphics.off()

```

```{r}

for (a in 1:nrow(location_summary)){
  location_summary[a, "order"] = 
    mapData[which.min(abs(location_summary[[a, "lat"]] - mapData$lat) + abs(location_summary[[a, "long"]] - mapData$long)), "order"]
}
```

```{r}
# location_map <- 
location_map <- full_join(mapData, location_summary, by = c("order"))
```

```{r}
#location_map$time = as.factor(location_map$time)
#location_map$time %>% fct_relevel
```

```{r}
gapCodes <- gapminder %>%
		filter(year == max(year)) %>%
		mutate(ISO = countrycode(country, "country.name", "iso2c"))

gapminder_map <- left_join(mapData, gapCodes, by = "ISO")
glimpse(gapminder_map)
```

```{r}
location_map <- location_map %>% 
  group_by(group) %>% 
  mutate(time = max(time, na.rm = TRUE), 
         count = max(count, na.rm = TRUE))
```

```{r}
ggplot(location_map %>% filter(region == "South Africa")) + 
	geom_polygon(aes(x = long.x, y = lat.x, group = group)) + 
  geom_point(aes(x = long.y, y = lat.y, colour = count)) + 
	labs(x = "Longitude", y = "Latitude") + 
  scale_colour_continuous()
	#scale_fill_continuous("Life\nexpectancy", labels = unit_format(unit = "years"))
```







